name: Coverage

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Just 📦
        uses: extractions/setup-just@v2
      - name: Install the latest version of uv 📦
        uses: astral-sh/setup-uv@v5
      - name: Install python 📦
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies 📦
        run: just install
      - name: Run tests and coverage
        run: |
          uv run coverage run -m pytest tests
          uv run coverage html --show-contexts --title "Coverage for ${{ github.sha }}"
      - name: Store coverage HTML
        uses: actions/upload-artifact@v3
        with:
          name: coverage-html
          path: htmlcov
