name: Coverage

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  FORCE_COLOR: 1    # Get colored pytest output

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest"

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pdm install

      - name: "Combine data"
        env:
          COVERAGE_RCFILE: "metacov.ini"
        run: |
          pdm run coverage combine
          coverage html --show-contexts --title "Coverage for ${{ github.sha }}"

      - name: Store coverage HTML
        uses: actions/upload-artifact@v3
        with:
          name: coverage-html
          path: htmlcov
